const QUESTIONS = {
    "Web Development": [
      "Explain the difference between HTML, CSS, and JavaScript and how they work together.",
      "What is the DOM and how do you manipulate it?",
      "Explain the concept of responsive design and how you implement it.",
      "What is the difference between GET and POST HTTP methods?",
      "Explain CSS flexbox and when you would use it over grid.",
      "What is a REST API and how does it work?",
      "What is the difference between localStorage and sessionStorage?",
      "Explain what CORS is and why it exists.",
      "What is the purpose of semantic HTML? Give examples.",
      "How does browser caching work and why is it important?",
      "What is the difference between == and === in JavaScript?",
      "Explain event bubbling and event capturing in JavaScript.",
      "What are CSS media queries and how do you use them?",
      "What is the purpose of the meta viewport tag?",
      "Explain the difference between inline, block, and inline-block elements.",
      "What is a Promise in JavaScript and how does it work?",
      "Explain async/await and how it differs from Promises.",
      "What is webpack and why is it used?",
      "What is the box model in CSS?",
      "Explain the difference between relative, absolute, and fixed positioning in CSS.",
      "What are web accessibility best practices?",
      "What is a 404 error and how do you handle it?",
      "Explain what an API endpoint is.",
      "What is the difference between a framework and a library?",
      "What is version control and why is it important?",
      "What is the purpose of a package.json file?",
      "Explain what npm is and how it works.",
      "What is a CDN and why would you use one?",
      "Explain the difference between client-side and server-side rendering.",
      "What is HTTPS and why is it important?"
    ],
    "Python": [
      "What is the difference between a list and a tuple in Python?",
      "Explain how Python's garbage collection works.",
      "What are decorators in Python and how do you use them?",
      "Explain the difference between shallow copy and deep copy.",
      "What is a generator in Python and when would you use one?",
      "Explain Python's GIL (Global Interpreter Lock).",
      "What is the difference between *args and **kwargs?",
      "Explain list comprehensions and give an example.",
      "What are Python's built-in data types?",
      "What is the difference between is and == in Python?",
      "Explain how exception handling works in Python.",
      "What is a lambda function in Python?",
      "Explain object-oriented programming concepts in Python.",
      "What is the difference between a class method and a static method?",
      "How does Python handle memory management?",
      "What are Python virtual environments and why use them?",
      "Explain the concept of inheritance in Python.",
      "What is pip and how do you use it?",
      "What is the purpose of __init__ in Python classes?",
      "Explain how file handling works in Python.",
      "What is a dictionary in Python and how is it different from a list?",
      "Explain the difference between append and extend for lists.",
      "What are Python modules and how do you import them?",
      "What is the difference between range and xrange?",
      "Explain how Python's map and filter functions work.",
      "What is a set in Python and what are its use cases?",
      "Explain Python's with statement and context managers.",
      "What is recursion and give an example in Python.",
      "Explain the difference between mutable and immutable objects.",
      "What are Python type hints and why use them?"
    ],
    "Data Science": [
      "What is the difference between supervised and unsupervised learning?",
      "Explain what overfitting is and how to prevent it.",
      "What is cross-validation and why is it important?",
      "Explain the difference between classification and regression.",
      "What is a confusion matrix and what metrics can you derive from it?",
      "Explain what feature engineering is and why it matters.",
      "What is the curse of dimensionality?",
      "Explain the bias-variance tradeoff.",
      "What is PCA and when would you use it?",
      "What is the difference between bagging and boosting?",
      "Explain what a p-value is in statistical testing.",
      "What is the difference between correlation and causation?",
      "Explain k-means clustering.",
      "What is gradient descent and how does it work?",
      "Explain what a decision tree is.",
      "What is a neural network at a high level?",
      "What is the difference between mean, median, and mode?",
      "Explain what data normalization is and why it's needed.",
      "What is the train-test split and why is it important?",
      "Explain what SQL joins are.",
      "What is exploratory data analysis?",
      "What is the difference between Type I and Type II errors?",
      "Explain what a random forest is.",
      "What is a ROC curve and AUC score?",
      "What tools and libraries do you use for data science?",
      "Explain what missing data imputation is.",
      "What is A/B testing?",
      "Explain what standard deviation measures.",
      "What is logistic regression used for?",
      "Explain what a data pipeline is."
    ],
    "Digital Marketing": [
      "What is SEO and how does it work?",
      "Explain the difference between organic and paid search.",
      "What is a conversion rate and how do you improve it?",
      "Explain what Google Analytics is used for.",
      "What is email marketing and best practices for it?",
      "What is content marketing and why is it important?",
      "Explain what social media marketing involves.",
      "What is a buyer persona and how do you create one?",
      "Explain what PPC advertising is.",
      "What is the difference between B2B and B2C marketing?",
      "What is a marketing funnel?",
      "Explain what remarketing is.",
      "What are KPIs in digital marketing?",
      "Explain what influencer marketing is.",
      "What is affiliate marketing?",
      "Explain what a landing page is and what makes it effective.",
      "What is the difference between impressions and clicks?",
      "Explain what CTR means and how to improve it.",
      "What is a marketing automation tool?",
      "What is customer lifetime value (CLV)?",
      "Explain what brand awareness means.",
      "What is a call to action (CTA)?",
      "Explain what bounce rate means.",
      "What is social proof and how is it used in marketing?",
      "What is an editorial calendar?",
      "Explain what keyword research involves.",
      "What is a backlink and why is it important for SEO?",
      "Explain what A/B testing is in marketing.",
      "What is customer acquisition cost (CAC)?",
      "Explain what omnichannel marketing means."
    ],
    "UI/UX Design": [
      "What is the difference between UI and UX design?",
      "Explain what a wireframe is and when you use it.",
      "What is a user persona and how do you create one?",
      "Explain the concept of design thinking.",
      "What is usability testing and why is it important?",
      "Explain what information architecture is.",
      "What are design patterns in UI/UX?",
      "What is the difference between a mockup and a prototype?",
      "Explain Gestalt principles in design.",
      "What is accessibility in design and why does it matter?",
      "What is a style guide and why is it important?",
      "Explain what responsive design means.",
      "What is the F-pattern in web design?",
      "Explain color theory basics for UI design.",
      "What is typography and how does it affect UX?",
      "What is a user journey map?",
      "Explain what card sorting is.",
      "What is the difference between heuristic evaluation and usability testing?",
      "What are microinteractions in UI design?",
      "Explain what white space is and why it matters.",
      "What design tools do you use and why?",
      "What is a design system?",
      "Explain what affordance means in UX.",
      "What is progressive disclosure in UX?",
      "Explain what the 80/20 rule means in UX.",
      "What is eye tracking in UX research?",
      "Explain what a call-to-action button best practices are.",
      "What is the mobile-first design approach?",
      "Explain what user onboarding is.",
      "What is a heatmap and how is it used in UX research?"
    ],
    "Content Writing": [
      "What is the difference between copywriting and content writing?",
      "Explain what SEO writing involves.",
      "What is a content strategy?",
      "How do you research topics for content?",
      "Explain what tone of voice means in writing.",
      "What is a headline formula and why does it matter?",
      "How do you write for different target audiences?",
      "What is long-form vs short-form content?",
      "Explain what a content brief is.",
      "What are the key elements of a good blog post?",
      "How do you measure content performance?",
      "What is storytelling in content marketing?",
      "Explain what evergreen content is.",
      "What is a content calendar and how do you use it?",
      "How do you handle writer's block?",
      "What is the inverted pyramid writing style?",
      "Explain what a meta description is.",
      "What are internal and external links in content?",
      "How do you repurpose content?",
      "What is plagiarism and how do you avoid it?",
      "What is a ghostwriter?",
      "Explain what content curation is.",
      "What is the difference between active and passive voice?",
      "How do you write an effective email newsletter?",
      "What is UGC (user-generated content)?",
      "Explain what a FAQ section is and when to use it.",
      "What are the best practices for writing social media posts?",
      "What is technical writing?",
      "Explain what a case study is in content marketing.",
      "What tools do you use for content writing and editing?"
    ],
    "Sales": [
      "What is the difference between B2B and B2C sales?",
      "Explain what a sales funnel is.",
      "What is cold calling and what makes it effective?",
      "How do you handle objections from a customer?",
      "What is SPIN selling?",
      "Explain what consultative selling is.",
      "What is a sales quota and how do you meet it?",
      "What is CRM and how do you use it?",
      "Explain what lead generation means.",
      "What is the difference between a lead and a prospect?",
      "What is upselling and cross-selling?",
      "How do you build rapport with a customer?",
      "What is a sales pitch and what makes it good?",
      "Explain what a pipeline is in sales.",
      "What is the challenger sale methodology?",
      "How do you qualify a lead?",
      "What is the difference between inside and outside sales?",
      "Explain what account management is.",
      "What is a follow-up strategy in sales?",
      "How do you handle a price objection?",
      "What is solution selling?",
      "Explain what a value proposition is.",
      "What metrics do you track in sales?",
      "What is churn rate in sales?",
      "How do you research a prospect before a call?",
      "Explain what social selling is.",
      "What is a sales playbook?",
      "How do you close a deal?",
      "What is customer retention and why does it matter?",
      "Explain what net promoter score (NPS) is."
    ],
    "Accounting": [
      "What is the difference between assets, liabilities, and equity?",
      "Explain what double-entry bookkeeping is.",
      "What is the difference between cash and accrual accounting?",
      "Explain what accounts payable and accounts receivable are.",
      "What is a balance sheet?",
      "What is a profit and loss statement?",
      "Explain what depreciation is.",
      "What is the difference between gross profit and net profit?",
      "What is working capital and how do you calculate it?",
      "Explain what a trial balance is.",
      "What is EBITDA?",
      "What is the difference between a debit and a credit?",
      "Explain what tax deductions are.",
      "What is financial forecasting?",
      "What is internal audit?",
      "Explain what cost of goods sold (COGS) is.",
      "What is a budget variance?",
      "Explain what amortization is.",
      "What is the matching principle in accounting?",
      "What is a journal entry?",
      "Explain what liquidity means in accounting.",
      "What is a cash flow statement?",
      "What are the different types of business expenses?",
      "Explain what GST/VAT is.",
      "What is a fixed asset?",
      "What is the difference between revenue and income?",
      "Explain what provisions in accounting are.",
      "What is an auditor's role?",
      "What is the going concern assumption?",
      "What accounting software have you used?"
    ],
    "JavaScript": [
      "What is the difference between var, let, and const?",
      "Explain closures in JavaScript.",
      "What is hoisting in JavaScript?",
      "Explain the event loop in JavaScript.",
      "What is prototypal inheritance?",
      "What is the difference between null and undefined?",
      "Explain what a callback function is.",
      "What is the spread operator and how do you use it?",
      "Explain what destructuring is in JavaScript.",
      "What are arrow functions and how do they differ from regular functions?",
      "What is the this keyword in JavaScript?",
      "Explain what a module is in JavaScript.",
      "What is JSON and how do you parse it?",
      "Explain fetch API and how to use it.",
      "What are higher-order functions?",
      "Explain what map, filter and reduce do.",
      "What is a Symbol in JavaScript?",
      "Explain what WeakMap and WeakSet are.",
      "What is optional chaining?",
      "Explain what async iterators are.",
      "What is the difference between synchronous and asynchronous code?",
      "What is event delegation?",
      "Explain what IIFE is.",
      "What is memoization?",
      "Explain what currying is.",
      "What are template literals?",
      "What is the nullish coalescing operator?",
      "Explain what a Proxy object is.",
      "What is the difference between deep and shallow equality?",
      "Explain what service workers are."
    ],
    "React": [
      "What is the virtual DOM and how does React use it?",
      "Explain the difference between state and props.",
      "What are React hooks and why were they introduced?",
      "Explain useState and useEffect hooks.",
      "What is the component lifecycle in React?",
      "What is JSX and how does it work?",
      "Explain what context API is used for.",
      "What is React Router and how does it work?",
      "What is the difference between controlled and uncontrolled components?",
      "Explain what useCallback and useMemo do.",
      "What is Redux and when would you use it?",
      "Explain what prop drilling is and how to avoid it.",
      "What is a higher-order component (HOC)?",
      "Explain what React.memo does.",
      "What are keys in React lists and why are they important?",
      "What is code splitting in React?",
      "Explain what lazy loading is in React.",
      "What is the useRef hook used for?",
      "What is server-side rendering in React?",
      "Explain what error boundaries are.",
      "What is the difference between class and functional components?",
      "What is Strict Mode in React?",
      "Explain what portals are in React.",
      "What is reconciliation in React?",
      "What is the useReducer hook?",
      "Explain what custom hooks are.",
      "What is Next.js and how does it relate to React?",
      "What is React Testing Library?",
      "Explain what Suspense is in React.",
      "What are render props?"
    ],
    "Machine Learning": [
      "What is the difference between machine learning and deep learning?",
      "Explain what a training dataset is.",
      "What is a loss function?",
      "Explain backpropagation.",
      "What is regularization and why is it used?",
      "Explain the difference between L1 and L2 regularization.",
      "What is a convolutional neural network (CNN)?",
      "Explain what transfer learning is.",
      "What is an RNN and what is it used for?",
      "What is LSTM and how does it solve vanishing gradients?",
      "Explain what a GAN is.",
      "What is reinforcement learning?",
      "Explain what hyperparameter tuning is.",
      "What is batch normalization?",
      "Explain what dropout is in neural networks.",
      "What is the softmax function?",
      "What is the difference between classification and object detection?",
      "Explain what NLP is.",
      "What is word embedding?",
      "What is BERT and what was its significance?",
      "What are transformers in ML?",
      "Explain what precision and recall are.",
      "What is the F1 score?",
      "Explain what ensemble methods are.",
      "What is XGBoost?",
      "Explain what k-nearest neighbors (KNN) is.",
      "What is support vector machine (SVM)?",
      "Explain what naive Bayes is.",
      "What is semi-supervised learning?",
      "Explain what model inference is."
    ],
    "Cybersecurity": [
      "What is the difference between authentication and authorization?",
      "Explain what SQL injection is and how to prevent it.",
      "What is XSS and how do you prevent it?",
      "What is CSRF and how do you defend against it?",
      "Explain what a firewall does.",
      "What is the difference between symmetric and asymmetric encryption?",
      "What is SSL/TLS and how does HTTPS work?",
      "Explain what a VPN is.",
      "What is phishing and how do you identify it?",
      "What is a man-in-the-middle attack?",
      "Explain what penetration testing is.",
      "What is the principle of least privilege?",
      "What is two-factor authentication?",
      "Explain what a DDoS attack is.",
      "What is a zero-day vulnerability?",
      "Explain what social engineering is.",
      "What is a brute force attack?",
      "What is hashing and how is it used in security?",
      "Explain what OAuth is.",
      "What is a security audit?",
      "What is OWASP and what is the OWASP Top 10?",
      "Explain what malware is and its types.",
      "What is a honeypot in cybersecurity?",
      "Explain what network segmentation is.",
      "What is multi-factor authentication?",
      "Explain what an intrusion detection system (IDS) is.",
      "What is ransomware?",
      "Explain what public key infrastructure (PKI) is.",
      "What is a security information and event management (SIEM) system?",
      "Explain what endpoint security is."
    ],
    "DevOps": [
      "What is DevOps and what problem does it solve?",
      "Explain what CI/CD means.",
      "What is Docker and why is it used?",
      "Explain what Kubernetes is.",
      "What is infrastructure as code (IaC)?",
      "Explain what a microservices architecture is.",
      "What is Git and how does it work?",
      "What is a container vs a virtual machine?",
      "Explain what monitoring and observability mean.",
      "What is blue-green deployment?",
      "Explain what a deployment pipeline is.",
      "What is Terraform used for?",
      "What is Ansible used for?",
      "Explain what load balancing is.",
      "What is a reverse proxy?",
      "Explain what auto-scaling is.",
      "What is a service mesh?",
      "What is helm in Kubernetes?",
      "Explain what GitOps is.",
      "What is a rolling deployment?",
      "Explain what log aggregation is.",
      "What is an SLA, SLO, and SLI?",
      "What is chaos engineering?",
      "Explain what a pod is in Kubernetes.",
      "What is Jenkins used for?",
      "What is GitHub Actions?",
      "Explain what artifact management is.",
      "What is a message queue and give an example.",
      "What is the CAP theorem?",
      "Explain what feature flags are."
    ],
    "Cloud Computing": [
      "What is cloud computing and what are its main benefits?",
      "What is the difference between IaaS, PaaS, and SaaS?",
      "Explain what AWS is and name 5 services.",
      "What is the difference between public, private, and hybrid cloud?",
      "What is serverless computing?",
      "Explain what S3 is used for.",
      "What is EC2 in AWS?",
      "Explain what auto-scaling is in cloud.",
      "What is a CDN and how does it work?",
      "What is cloud security and shared responsibility model?",
      "Explain what Lambda functions are.",
      "What is the difference between vertical and horizontal scaling?",
      "What is a VPC in cloud computing?",
      "Explain what cloud migration means.",
      "What is multi-cloud strategy?",
      "Explain what object storage is.",
      "What is a managed database service?",
      "What is cloud cost optimization?",
      "Explain what high availability means in cloud.",
      "What is disaster recovery in cloud?",
      "What is Google Cloud Platform?",
      "Explain what Azure Active Directory is.",
      "What is a cloud region and availability zone?",
      "What is Elastic Load Balancing?",
      "Explain what CloudWatch is.",
      "What is a container registry?",
      "What is API Gateway in cloud?",
      "Explain what DynamoDB is.",
      "What is cloud storage vs cloud computing?",
      "What certifications are important in cloud computing?"
    ],
    "Graphic Design": [
      "What is the difference between raster and vector graphics?",
      "Explain what CMYK and RGB color modes are used for.",
      "What is typography and what makes good font pairing?",
      "What is the rule of thirds in design?",
      "Explain what kerning, leading, and tracking are.",
      "What design software do you use and why?",
      "What is a brand identity and what does it include?",
      "Explain what a mood board is.",
      "What is the difference between a logo and a brand?",
      "What is negative space in design?",
      "Explain what DPI and PPI mean.",
      "What is a grid system in graphic design?",
      "What is color psychology in design?",
      "Explain the difference between serif and sans-serif fonts.",
      "What is a design brief?",
      "What is print design vs digital design?",
      "Explain what a bleed is in print design.",
      "What is a mockup in graphic design?",
      "What is the golden ratio?",
      "Explain what visual hierarchy means.",
      "What is a typeface vs a font?",
      "What are complementary colors?",
      "Explain what a flat design style is.",
      "What is minimalism in design?",
      "What are design trends you follow?",
      "Explain what iconography is.",
      "What is a style tile?",
      "What is the difference between illustration and photography in design?",
      "Explain what an infographic is.",
      "What is brand consistency and why does it matter?"
    ],
    "Project Management": [
      "What is the difference between Agile and Waterfall?",
      "Explain what a sprint is in Scrum.",
      "What is a project charter?",
      "Explain what a Gantt chart is.",
      "What is the critical path method?",
      "What is risk management in projects?",
      "Explain what a stakeholder is.",
      "What is scope creep and how do you manage it?",
      "What is a project kickoff meeting?",
      "Explain what KPIs are in project management.",
      "What is a RACI matrix?",
      "What is a project baseline?",
      "Explain what a retrospective is.",
      "What is the triple constraint in project management?",
      "What project management tools do you use?",
      "What is a change request in project management?",
      "Explain what resource allocation is.",
      "What is the difference between a project manager and a product manager?",
      "What is earned value management?",
      "Explain what a work breakdown structure (WBS) is.",
      "What is Kanban?",
      "What is a dependency in project management?",
      "Explain what a project milestone is.",
      "What is a project post-mortem?",
      "What is the role of communication in project management?",
      "Explain what daily standups are.",
      "What is a project budget and how do you manage it?",
      "What is quality assurance in project management?",
      "Explain what procurement management is.",
      "What certifications are valuable in project management?"
    ]
  };
  
  const ACHIEVEMENT_QUESTIONS = [
    "Tell us about your biggest professional achievement or project. What was your role, what challenges did you face, and what was the outcome?",
    "Describe a project you are most proud of. What skills did you use and what impact did it have?",
    "Tell us about a time you solved a difficult problem at work. What was your approach?",
    "Describe the most challenging project you have worked on and how you overcame the obstacles.",
    "What is the most significant contribution you have made in your career so far?"
  ];
  
  const GENERAL_QUESTIONS = [
    "You have 8 balls, one of which is slightly heavier. Using a balance scale, what is the minimum number of weighings needed to find the heavier ball?",
    "How would you explain the internet to someone who has never used it before?",
    "If you had to improve any everyday object to make it 10x better, what would you choose and how would you improve it?",
    "A company's revenue doubled but profits dropped. What are the possible reasons?",
    "How do you prioritize tasks when everything seems urgent?",
    "If you could add one feature to any popular app or website, what would it be and why?",
    "How would you explain your primary skill to a 10-year-old?",
    "You are given a task with unclear requirements. What steps do you take?",
    "What do you think will be the biggest change in your field in the next 5 years?",
    "Describe your ideal work environment and why it helps you perform best."
  ];
  
  function getRandomItems(arr, count) {
    const shuffled = [...arr].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
  }
  
  export default async function handler(req, res) {
    if (req.method !== "POST")
      return res.status(405).json({ error: "Method not allowed" });
  
    const { skill } = req.body;
  
    const skillQuestions = QUESTIONS[skill] || QUESTIONS["Web Development"];
    const selected = getRandomItems(skillQuestions, 8);
    const achievement = getRandomItems(ACHIEVEMENT_QUESTIONS, 1);
    const general = getRandomItems(GENERAL_QUESTIONS, 1);
  
    const questions = [...selected, ...achievement, ...general];
  
    return res.status(200).json({ questions });
  }